### ISSUE TITLE
Chess Game Bug

### ISSUE THREAD

**Issue by ashumeow** [ashumeow/Cplusplus-Chess-Game#1]
prog.cpp:1:22: fatal error: graphics.h: No such file or directory
 #include <graphics.h>
                      ^
compilation terminated.

**Comment by ashumeow** [comment]
Current bugs:-

prog.cpp:26:11: error: '::main' must return 'int'
 void main()
           ^
prog.cpp: In function 'int main()':
prog.cpp:30:16: error: 'DETECT' was not declared in this scope
  int gdriver = DETECT;
                ^
prog.cpp:32:47: error: 'initgraph' was not declared in this scope
  initgraph(&gdriver,&gmode,"e:\borlandc\bgi");
                                               ^
prog.cpp:37:14: error: 'setcolor' was not declared in this scope
   setcolor(12);
              ^
prog.cpp:38:18: error: 'HORIZ_DIR' was not declared in this scope
   settextstyle(4,HORIZ_DIR,i);
                  ^
prog.cpp:38:29: error: 'settextstyle' was not declared in this scope
   settextstyle(4,HORIZ_DIR,i);
                             ^
prog.cpp:39:42: error: 'outtextxy' was not declared in this scope
   outtextxy(50,120,"WELCOME TO THE CHESS");
                                          ^
prog.cpp:40:11: error: 'delay' was not declared in this scope
   delay(30);
           ^
prog.cpp:41:15: error: 'cleardevice' was not declared in this scope
   cleardevice();
               ^
prog.cpp:43:41: error: 'outtextxy' was not declared in this scope
  outtextxy(50,120,"WELCOME TO THE CHESS");
                                         ^
prog.cpp:44:17: error: 'HORIZ_DIR' was not declared in this scope
  settextstyle(1,HORIZ_DIR,3);
                 ^
prog.cpp:44:28: error: 'settextstyle' was not declared in this scope
  settextstyle(1,HORIZ_DIR,3);
                            ^
prog.cpp:45:8: error: 'getch' was not declared in this scope
  getch();
        ^
prog.cpp:46:14: error: 'cleardevice' was not declared in this scope
  cleardevice();
              ^
prog.cpp:49:11: error: 'CYAN' was not declared in this scope
  setcolor(CYAN);
           ^
prog.cpp:49:15: error: 'setcolor' was not declared in this scope
  setcolor(CYAN);
               ^
prog.cpp:103:1: error: 'cout' was not declared in this scope
 cout<<"\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b Enter File name to save \n";
 ^
prog.cpp:103:1: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:104:5: error: 'cin' was not declared in this scope
     cin>>strFileName;  //Enter File Name
     ^
prog.cpp:104:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:60:18: note:   'std::cin'
   extern istream cin;  /// Linked to standard input
                  ^
prog.cpp:146:1: error: 'cout' was not declared in this scope
 cout<<"\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b Enter File name to Load \n";
 ^
prog.cpp:146:1: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:147:7: error: 'cin' was not declared in this scope
       cin>>strFileName;
       ^
prog.cpp:147:7: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:60:18: note:   'std::cin'
   extern istream cin;  /// Linked to standard input
                  ^
prog.cpp:201:5: error: 'cout' was not declared in this scope
     cout<<ch;
     ^
prog.cpp:201:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:209:5: error: 'cout' was not declared in this scope
     cout<<ch;
     ^
prog.cpp:209:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:240:5: error: 'cout' was not declared in this scope
     cout<<"\nenter final position  ¯ ";
     ^
prog.cpp:240:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:248:5: error: 'cout' was not declared in this scope
     cout<<ch;
     ^
prog.cpp:248:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:256:5: error: 'cout' was not declared in this scope
     cout<<ch;
     ^
prog.cpp:256:5: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:301:1: error: 'cout' was not declared in this scope
 cout<<"\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b which piece Q,R,H,B";
 ^
prog.cpp:301:1: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp: In function 'void printboard()':
prog.cpp:406:14: error: 'WHITE' was not declared in this scope
     setcolor(WHITE);
              ^
prog.cpp:406:19: error: 'setcolor' was not declared in this scope
     setcolor(WHITE);
                   ^
prog.cpp:408:14: error: 'BLACK' was not declared in this scope
     setcolor(BLACK);
              ^
prog.cpp:408:19: error: 'setcolor' was not declared in this scope
     setcolor(BLACK);
                   ^
prog.cpp:410:42: error: 'outtextxy' was not declared in this scope
    outtextxy(270+(j_45),105+(i_45),"ÛÛ");
                                          ^
prog.cpp:414:14: error: 'GREEN' was not declared in this scope
     setcolor(GREEN);
              ^
prog.cpp:414:19: error: 'setcolor' was not declared in this scope
     setcolor(GREEN);
                   ^
prog.cpp:416:15: error: 'setcolor' was not declared in this scope
     setcolor(9);
               ^
prog.cpp: In function 'void wrongStart()':
prog.cpp:441:2: error: 'cout' was not declared in this scope
  cout<<"\nWrong Input\nPress any key to continue...";
  ^
prog.cpp:441:2: note: suggested alternative:
In file included from prog.cpp:4:0:
/usr/include/c++/4.9/iostream:61:18: note:   'std::cout'
   extern ostream cout;  /// Linked to standard output
                  ^
prog.cpp:442:16: error: 'getch' was not declared in this scope
  char ch=getch();
                ^
prog.cpp:449:14: error: 'gotoxy' was not declared in this scope
    gotoxy(i,j);
              ^
prog.cpp:452:12: error: 'gotoxy' was not declared in this scope
  gotoxy(1,1);
            ^
prog.cpp: At global scope:
prog.cpp:457:2: error: expected unqualified-id before 'for'
  for(int i=1;i<=27;i++)
  ^
prog.cpp:457:14: error: 'i' does not name a type
  for(int i=1;i<=27;i++)
              ^
prog.cpp:457:20: error: 'i' does not name a type
  for(int i=1;i<=27;i++)
                    ^
prog.cpp:458:15: error: 'j' does not name a type
   for(int j=1;j<=8;j++){
               ^
prog.cpp:458:20: error: 'j' does not name a type
   for(int j=1;j<=8;j++){
                    ^
prog.cpp:462:8: error: expected constructor, destructor, or type conversion before '(' token
  gotoxy(1,1);
        ^
prog.cpp:463:2: error: 'cout' does not name a type
  cout<<"enter initial position ¯ ";
  ^
prog.cpp:464:1: error: expected declaration before '}' token
 }
 ^

**Comment by iamOgunyinka** [comment]
`void main()` -- This should be `int main()`, this is C++, not C.

Are you making use of OpenGL and not including the header? What's `memory` doing in the code? You're not making any use of it.

> prog.cpp:103:1: error: 'cout' was not declared in this scope

Import the whole `std` namespace or prefix the standard objects/stream with `std::`.

Have fun,
Josh

-----Original Message-----

**Comment by ashumeow** [comment]
yeah yeah... graphics complexity. The whole code needs to be re-coded again :|
